---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts/{post_id}/comments":
    post:
      summary: Creates a comment
      tags:
      - Comments
      parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: comment created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
              - content
          application/xml:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
              - content
    get:
      summary: Retrieves comments for a post
      tags:
      - Comments
      parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: object
                required:
                - comments
            application/xml:
              schema:
                type: object
                properties:
                  comments:
                    type: object
                required:
                - comments
        '404':
          description: Not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
